# Generated by Django 4.0.4 on 2023-05-03 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.CharField(max_length=64)),
                ('short', models.CharField(max_length=8)),
                ('name', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.CharField(max_length=64)),
                ('event_id', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=64)),
                ('tennant_id', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('genre', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('status_changed_date', models.DateTimeField(blank=True, null=True)),
                ('buffs', models.ManyToManyField(blank=True, to='web.buff')),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollArbitrary',
            fields=[
                ('tennant_id', models.CharField(max_length=64)),
                ('poll_id', models.TextField(primary_key=True, serialize=False)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('poll_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('tennant_id', models.CharField(max_length=64)),
                ('poll_id', models.TextField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('poll_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviesuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='AntiInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.CharField(max_length=64)),
                ('poll_id', models.TextField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.CharField(max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
        migrations.CreateModel(
            name='CriticRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
