# Generated by Django 4.0.4 on 2022-05-25 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_criticrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criticrating',
            unique_together={('user', 'film')},
        ),
    ]
