# Generated by Django 4.0.4 on 2022-05-25 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_moviesuggestion_expressed_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesuggestion',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='watched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
