# Generated by Django 4.0.4 on 2022-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_moviesuggestion_added_moviesuggestion_watched_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=8)),
                ('name', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moviesuggestion',
            name='cage_factor',
        ),
        migrations.RemoveField(
            model_name='moviesuggestion',
            name='rock_factor',
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='buffs',
            field=models.ManyToManyField(blank=True, to='web.buff'),
        ),
    ]
