# Generated by Django 4.0.4 on 2022-05-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_buff_remove_moviesuggestion_cage_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.TextField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('poll_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviesuggestion')),
            ],
        ),
    ]
