# Generated by Django 4.0.4 on 2022-05-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesuggestion',
            name='meta',
            field=models.TextField(null=True),
        ),
    ]
