# Generated by Django 4.0.4 on 2022-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_watched_moviesuggestion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesuggestion',
            name='status',
            field=models.IntegerField(),
        ),
    ]
