# Generated by Django 4.0.4 on 2022-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_moviesuggestion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollArbitrary',
            fields=[
                ('poll_id', models.TextField(primary_key=True, serialize=False)),
                ('metadata', models.TextField()),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('poll_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
