# Generated by Django 4.0.4 on 2023-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_antiinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=32)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
